# playbooks/get_config_rpc.yml
---
- name: Get config via RPC directo
  hosts: huawei_routers
  gather_facts: false

  tasks:
    - name: Ejecutar CLI via NETCONF
      ansible.netcommon.netconf_rpc:
        rpc: 1013
        xmlns: "urn:ietf:params:xml:ns:netconf:base:1.0"
        content: <name/><model/><esn/><mac-address/><vendor/><state/><version/><patch-version/><configuration-file><current-file-name/></configuration-file><performance><cpu-using-rate/><memory-using-rate/><storages-using-rate/></performance><clock><current-datetime/><boot-datetime/><up-times/></clock>
      register: resultado
