# playbooks/get_interfaces.yml
---
- name: Leer interfaces via NETCONF
  hosts: huawei_routers
  gather_facts: false

  tasks:
    - name: Obtener interfaces
      ansible.netcommon.netconf_get:
        display: pretty
        filter: '''<ifm xmlns="urn:huawei:yang:huawei-ifm"> 
                <interfaces> 
                    <interface> 
                        <name/> 
                    </interface> 
                </interfaces> 
            </ifm>'''
      register: resultado