[huawei_routers]
ar5710_prueba ansible_host=192.168.150.201

[huawei_routers:vars]
ansible_connection=ansible.netcommon.netconf
ansible_port=830
ansible_user=netconf
ansible_password=Admin@1234
ansible_netconf_host_key_checking=false